name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Personal metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          base: "header, repositories"
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Paris
          config_padding: 10%
      
      - name: Personal Activities
        uses: lowlighter/metrics@latest
        with:
          filename: activity.svg
          base: "activity, community, metadata"
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_padding: 10%
          
      - name: Calendar
      # See action.yml for all options
        uses: lowlighter/metrics@latest
        with:
          filename: calendar.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # GITHUB_TOKEN is a special auto-generated token restricted to current repository, which is used to push files in it
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          base: ""
          config_padding: 10%
          
      - name: Plugin Languages
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_languages: yes
          plugin_languages_ignored: "Yacc, css, vim, html, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, Makefile, Ruby, Vim Script, Python, ApacheConf" # List of comma separated languages to ignore
          plugin_languages_skipped: "" # List of comma separated repositories to skip
          base: ""
          plugin_topics: yes
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          config_padding: 10%

      
      - name: Plugin Posts Dev.to
        uses: lowlighter/metrics@latest
        with:
          filename: posts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_posts: yes
          plugin_posts_source: dev.to
          base: ""

          
      - name: Plugin Habits
        uses: lowlighter/metrics@latest
        with:
          filename: habits.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          plugin_habits: yes
          plugin_habits_from: 220
          plugin_habits_days: 15
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          base: ""
          config_timezone: Europe/Paris
          
      - name: Plugin Stackoverflow
        uses: lowlighter/metrics@latest
        with:
          filename: stack.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 1633187                           # Stackoverflow user id (required)
          plugin_stackoverflow_sections: answers-top # Display top answers and recent questions
          plugin_stackoverflow_limit: 1                                # Display 2 entries per section
          plugin_stackoverflow_lines: 1                                # Display 4 lines per entry

      - name: Rss Plugin
        uses: lowlighter/metrics@latest
        with:
          filename: rss.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_rss: yes
          plugin_rss_source: https://domenicoluciani.com/feed.xml  # RSS feed
          plugin_rss_limit: 5                                  # Limit to 6 items
